Use the timezone inside the component instead of passing it 5x
arkime/arkime pull request #1659
Opened 2021-03-26 02:42 UTC by rnbwdsh

2021-03-26 13:49 UTC, 31453 commented
@rnbwdsh Thanks! This is a good idea. The MolochTime component does indeed have a getter for the user object which includes their timezone setting. The same goes for the MolochSearch component.

However, the MolochTime and MolochSearch components also need to be updated to exclude the `timezone` prop and use `user.settings.timezone` instead.

Also, I'm going to mark this PR and issue with the HackTogether label. If you want swag, please [sign-up](https://yahoo.github.io/hacktogether/) for Yahoo! Hack Together, if you have not done so, yet.

2021-03-26 14:16 UTC, 31453 requested changes
MolochTime and MolochSearch components also need to be updated to exclude the `timezone` prop and use `user.settings.timezone` instead.

2021-03-26 14:21 UTC, rnbwdsh commented
> Good idea, I'll fix that too.
In SessionField, it uses
`this.timezone || this.$store.state.user.settings.timezone,`
Whereas the passed in timezone is from the user.settings anyways, so the whole `this.timezone ||` can be omitted as well as the prop.

In fact I could edit it out in most places without any side-effects.

2021-03-26 14:22 UTC, 31453 commented
That's a great idea!

2021-03-26 14:59 UTC, 31453 commented
Also, it looks like the user object from the store is not available at the time that the `datePickerOptions` is being initialized. So, you'll have to wait to set `datePickerOptions` and initialize the time fields until the user object is available.

2021-03-26 15:02 UTC, 31453 commented
And FYI: it looks like there's an existing bug when changing the user timezone settings. It always sets the timezone to the previously selected setting. I'm created a new issue to reference this: #1667 No need to fix it in this PR unless you want to. I just wanted to make you aware of this issue.

2021-03-26 19:41 UTC, 31453 requested changes
just a few minor changes with `this.$store.state.user.settings.timezone`

2021-03-26 19:41 UTC, 31453 commented on viewer/vueapp/src/components/sessions/StickySessions.vue
> +      return this.$store.state.user.timezone;
needs to be `this.$store.state.user.settings.timezone`

2021-03-26 19:41 UTC, 31453 commented on viewer/vueapp/src/components/visualizations/Visualizations.vue
> +      return this.$store.state.user.timezone;
needs to be `this.$store.state.user.settings.timezone`

2021-04-05 20:35 UTC, rnbwdsh commented
Rebased + Fixed by now, thanks for the great support @31453.

2021-04-05 21:01 UTC, 31453 approved these changes

2021-04-05 21:01 UTC, 31453 commented
Looks great! Thanks for all the hard work ✨

2021-04-05 21:01 UTC, merged