crud info field column layout on sessions page
arkime/arkime pull request #2741
Opened 2024-04-04 18:55 UTC by 31453

rename everything LAYOUT instead of CONFIG

fixes [#2688](https://github.com/arkime/arkime/issues/2688)

## License
I confirm that this contribution is made under an Apache 2.0 license and that I have the authority necessary to make this contribution on behalf of its copyright owner.

2024-04-04 18:56 UTC, 31453 commented
Still need to display default arkime info field column layout and TESTSSSSSS

2024-04-11 16:03 UTC, awick requested changes
* CHANGELOG
* foo || [] should be foo ?? [] right?

2024-04-11 16:04 UTC, awick commented on viewer/apiUsers.js
> +  static #userInfoFields (user) {
this method only used in one place and couldn't it just be `user.?infoFieldsConfigs ?? []` :)

2024-04-11 16:06 UTC, awick commented on viewer/apiUsers.js
> +    user.spiviewFieldConfigs = user.spiviewFieldConfigs || [];
user.spiviewFieldConfigs ??= []

2024-04-11 16:07 UTC, awick commented on viewer/apiUsers.js
> +    if (req.params.type === 'sessionstable') {
switch!

2024-04-11 21:04 UTC, awick submitted a review, later dismissed

2024-04-12 16:36 UTC, awick approved these changes

2024-05-09 16:55 UTC, merged