Set OIDC redirect_uri dynamically if needed
arkime/arkime pull request #2950
Opened 2024-09-25 11:01 UTC by divinehawk

Setting authRedirectURIs to more than one URL (comma separated), results in no redirect_uri being used. This is because the redirect_uri has to be specified if client.redirect_uris isn't set to a single uri.

This commit sets the redirect_uri dynamically based on the hostname and path.

Fixes #2949

## License
I confirm that this contribution is made under an Apache 2.0 license and that I have the authority necessary to make this contribution on behalf of its copyright owner.

2024-09-25 11:27 UTC, divinehawk commented
Also this removes the requirement to set authRedirectURIs. So either 0 or more than 1 value will result in the dynamic setting. Original behavior is preserved.

2024-10-07 14:57 UTC, awick requested changes

2024-10-07 16:34 UTC, divinehawk commented on common/auth.js
> +    if (Auth.#strategies.includes('oidc') && (Auth.#authConfig.redirectURIs == '' || Auth.#authConfig.redirectURIs.split(',').length > 1)) {
Done!

2024-10-07 19:00 UTC, awick approved these changes

2024-10-07 19:01 UTC, merged